version: '3.8'
services:
 db:
   container_name: yt_db_container
   image: postgres
   restart: always
   environment:
     POSTGRES_DB: yt_coffee_db
     POSTGRES_USER: root
     POSTGRES_PASSWORD: secret
     PGDATA: /var/lib/postgresql/data
   hostname: postgres 
   ports:
     - "5438:5432"
   volumes:
     - db-data:/var/lib/postgresql/data

volumes:
 db-data:

